# schema.yml

version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Sales of Greenweez. We have one row per product_id found in each orders_id."
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "date_date"  # Pas besoin de CAST ici, il est fait dans SQL, cela peut générer une erreur
        tests:
          - unique:
              column_name: "orders_id || '-' || pdt_id"
          - not_null:
              column_name: "orders_id || '-' || pdt_id"

      - name: product
        identifier: gz_raw_product
        description: "Product catalog from Greenweez."
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: "All shipping data from Greenweez."
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: "data for adwords"
        tests:
          - unique:
              column_name: "campaign_key || '-' || date_date"
          - not_null:
              column_name: "campaign_key || '-' || date_date"
      - name: bing
        identifier: raw_gz_bing
        description: "data for bing"
        tests:
          - unique:
              column_name: "campaign_key || '-' || date_date"
          - not_null:
              column_name: "campaign_key || '-' || date_date"

      - name: criteo
        identifier: raw_gz_criteo
        description: "data for criteo"
        tests:
          - unique:
              column_name: "campaign_key || '-' || date_date"
          - not_null:
              column_name: "campaign_key || '-' || date_date"
      - name: facebook
        identifier: raw_gz_facebook
        description: "data for facebook"
        tests:
          - unique:
              column_name: "campaign_key || '-' || date_date"
          - not_null:
              column_name: "campaign_key || '-' || date_date"

models:
  - name: int_orders_margin
    description: "Description orders margin."
    columns:
      - name: orders_id
        description: "Clé primaire."
        tests:
          - unique
          - not_null

  - name: int_orders_operational
    description: "Description orders operational."
    columns:
      - name: orders_id
        description: "Clé primaire."

  - name: finance_days
    columns:
      - name: date_date
        description: "Clé primaire."
        tests:
          - unique
          - not_null
  - name: int_sales_margin
    columns:
      - name: orders_id
        description: "Clé primaire."
        tests:
          - not_null
     
  - name: int_campaigns
    tests: 
    - unique:
       column_name: "campaign_key || '-' || date_date"

  - name: int_campaigns_day
    description: "data from all campaigns per day"
    columns: 
      - name: date_date
        tests:
          - unique
          - not_null


  - name: finance_campaigns_day
    description: "data from all campaigns per day & finance data"
    columns: 
      - name: date_date
        tests:
          - unique
          - not_null

  - name: finance_campaigns_month
    description: "data from all campaigns per month & finance data"
    columns: 
      - name: datemonth
        tests:
          - unique
          - not_null
