 # schema.yml

 version: 2

 sources:
   - name: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
       - name: product
         identifier: gz_raw_product
       - name: ship
         identifier: raw_gz_ship

