 # schema.yml

 version: 2

 sources:
   - name: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         freshness:
           warn_after: {count: 90 , period: day}
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         tests:
          - unique:
              column_name: "(orders_id||'-'|| pdt_id)" 
          - not_null:
              column_name: "(orders_id||'-'|| pdt_id)"

       - name: product
         identifier: gz_raw_product
         description: product catalog from Greenweez
         columns:
          - name: products_id
            tests:
             - unique
             - not_null
       - name: ship
         identifier: raw_gz_ship
         description: all shipping from Greenweer
         columns:
          - name: orders_id
            tests:
             - unique
             - not_null

